backend:
  name: github
  repo: Dohungprovip/2-Player-game
  branch: main 

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "posts"
    create: true
    fields:
      - { name: "title", label: "Tiêu đề", widget: "string" }
      - { name: "body", label: "Nội dung", widget: "markdown" }
